global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'monitoring'
    static_configs:
    - targets: ['192.168.111.203:9090'] 
  - job_name: 'pipelines'
    static_configs:
    - targets: ['192.168.111.201:9100'] 
  - job_name: 'containers'
    static_configs:
    - targets: ['192.168.111.202:9100']
  - job_name: 'docker'
    static_configs:
    - targets: ['192.168.111.202:7070']