# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "server" do |server|
    server.vm.box = "shekeriev/centos-stream-8"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.99.101"
    server.vm.provision "shell", path: "add-hosts.sh"
    server.vm.provision "shell", path: "elk-install.sh"
    # server.vm.provision "shell", path: "create-kabana-index.sh" # Sometimes Kibana is not running -> set up is in trigger
    server.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 6144
      v.cpus = 2
    end
  end
  
  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/bionic64"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.99.102"
    node1.vm.provision "shell", path: "add-hosts.sh"
    node1.vm.provision "shell", path: "debian-metricbeat-install.sh"
    node1.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
  end
  
  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/bionic64"
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "192.168.99.103"
    node2.vm.provision "shell", path: "add-hosts.sh"
    node2.vm.provision "shell", path: "debian-metricbeat-install.sh"
    node2.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
  end

  config.trigger.after :up do |trigger|
        trigger.only_on = "node2"
        trigger.info = "* Create Kibana index Trigger"
        trigger.run = {inline: "vagrant ssh -c 'sudo /vagrant/create-kabana-index.sh' server"}
  end         
end