{
 "title": "Exam Board",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU load of the monitored hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (instance) (irate(process_cpu_seconds_total[10m]))"
    }
   ]
  },
  {
   "title": "RAM utilization of the monitored hosts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_Active_bytes" }
   ]
  },
  {
   "title": "Containers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=\"docker\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  }
 ]
}