# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "shekeriev/centos-stream-8"
    config.vm.hostname = "docker.do1.lab"
    config.vm.network "private_network", ip: "192.168.99.100"
    config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct:true
    config.vm.provision "docker" do |docker|
      docker.build_image "/vagrant",
        args: "-t centos_web_server"
      docker.run "web_server",
        image: "centos_web_server",
        args: "-p 8080:80"
    end
end