version: "3.8"
services:
    web:
        image: veselinovstf/nginx-php-bgapp
        deploy:
            replicas: 3
        ports:
            - 8080:8080
        networks:
            - app-network
    db:
        image: veselinovstf/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
networks:
    app-network:
