global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
    - targets: ['192.168.99.100:7070']  # docker metrics
  - job_name: 'applications'
    static_configs:
    - targets: ['192.168.99.100:8090'] # goprom app 1 metrics
    - targets: ['192.168.99.100:8099'] # goptom app 2 metrics
